<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
xmlns:html="http://www.w3.org/TR/REC-html40"
xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>XML Sitemap</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
    color: #333;
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
}
h1 {
    color: #005fcc;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin-top: 20px;
}
th, td {
    padding: 10px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}
th {
    background-color: #f8f9fa;
    font-weight: 600;
}
tr:hover {
    background-color: #f5f5f5;
}
a {
    color: #005fcc;
    text-decoration: none;
}
a:hover {
    text-decoration: underline;
}
.header {
    background-color: #eef4ff;
    padding: 15px;
    border-radius: 8px;
    margin-bottom: 20px;
    border: 1px solid #d0e1fd;
}
</style>
</head>
<body>
<div class="header">
    <h1>XML Sitemap</h1>
    <p>This is a XML Sitemap generated by SmartReception.ai to allow search engines (like Google) to crawl the website. The file is created automatically.</p>
</div>
<table>
<tr>
    <th>URL</th>
    <th>Last Modified</th>
    <th>Change Frequency</th>
    <th>Priority</th>
</tr>
<xsl:for-each select="sitemap:urlset/sitemap:url">
<tr>
    <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
    <td><xsl:value-of select="sitemap:lastmod"/></td>
    <td><xsl:value-of select="sitemap:changefreq"/></td>
    <td><xsl:value-of select="sitemap:priority"/></td>
</tr>
</xsl:for-each>
</table>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
